### ISSUE TITLE
To deploy ICAP server in VPC environment AWS

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-icap-ova-security#1]
To deploy ICAP server in VPC environment AWS (using the latest OVA). 
The further OVA and information can be fetched from the below repository.
https://github.com/k8-proxy/GW-Releases/actions?query=workflow%3Aicap-server

**Comment by gurunathg** [comment]
@kumarsudhish Created stack and shared details. Please confirm if we can mark this issue as closed

**Comment by gurunathg** [comment]
Created and shared stack details. Closing this issue
