### ISSUE TITLE
To prepare a test to prove that traffic is getting routed through ICAP port

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-icap-ova-security#2]
Making sure and providing evidence that we are only sending traffic through the ICAP Port (in and out). 

**Output**
Basically to prove that there is not traffic that flights away from the OVA. To showcase the VPC logs that the traffic is going correctly.

Proving that the ICAP AMI doesn't generate any inbound and outbound traffic (apart from ICAP and HTTPs traffic). Start with VPC Flow Logs since that seems easier, also to see what these tools can do with AWS VPC Traffic Mirroring (https://aws.amazon.com/blogs/aws/new-vpc-traffic-mirroring/)

**Comment by michaelhidalgo** [comment]
Hey @kumarsudhish , doing a quick network scan on this deployment, it seems like the following ports are open. ICAP uses TCP 1344/1345.

Note that SSH should also be filtered. But we need to find out and document what that other ports are and why they need to be open. Having such mapping is important to understand the attack surface.


![Screen Shot 2021-02-15 at 14 36 30](https://user-images.githubusercontent.com/1732035/107990985-3ed9b080-6f9b-11eb-8b6c-71219c16b264.png)


Next step would be configure the VPC so we ca send the flow logs to CloudWatch

- https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch-logs-and-interface-VPC.html
- https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html#flow-logs-fields

**Comment by michaelhidalgo** [comment]
Same happens for the other IP Address behind the Load Balancer:
![Screen Shot 2021-02-15 at 16 00 04](https://user-images.githubusercontent.com/1732035/107996821-e6a8ab80-6fa6-11eb-80a4-b0d3db2fded5.png)

**Comment by michaelhidalgo** [comment]
Ok thanks, a part from the ports mentioned about that we need to document, we are setting up Cloudwatch logs.

Open question for @DinisCruz  and @kumarsudhish  is the aggregation interval settings. It can be 10 minutes or 1 minute.

1. 1 minute intervals which produces higher volume of logs than flows with a maximum aggregation interval of 10 min.
2. It takes additional time to process and publish the data to CloudWatch Logs or Amazon S3. This additional time could be around 5 minutes to publish to CloudWatch Logs.

This means it will be that the logs will be delayed for around ~7 minutes if the interval is 1 minute and ~17 minutes if the interval is 10 minutes, so it will be quasy-realtime.



```
The aggregation interval is the period of time during which a particular flow is captured and aggregated into a flow log record. By default, the maximum aggregation interval is 10 minutes. When you create a flow log, you can optionally specify a maximum aggregation interval of 1 minute. Flow logs with a maximum aggregation interval of 1 minute produce a higher volume of flow log records than flow logs with a maximum aggregation interval of 10 minutes.

When a network interface is attached to a Nitro-based instance, the aggregation interval is always 1 minute or less, regardless of the specified maximum aggregation interval.

After data is captured within an aggregation interval, it takes additional time to process and publish the data to CloudWatch Logs or Amazon S3. This additional time could be around 5 minutes to publish to CloudWatch Logs, and around 10 minutes to publish to Amazon S3. The flow logs service delivers within this additional time in a best effort manner. In some cases, your logs might be delayed beyond the 5 to 10 minutes additional time mentioned previously.```

**Comment by michaelhidalgo** [comment]
This is a high level diagram on the AWS Setup:

![ICAP AWS FLOW](https://user-images.githubusercontent.com/1732035/108094898-e7901a80-7044-11eb-9577-593e7e25fd51.png)

**Comment by dinis-cruz-gw** [comment]
@michaelhidalgo for this first phase (where we want to show the traffic) go for 1-minute intervals

When I tried it, the Cloudwatch logs were being updated reasonably quickly

**Comment by michaelhidalgo** [comment]
Awesome, @kumarsudhish  we can close this now.

**Comment by GINAGC** [comment]
Work completed
