### ISSUE TITLE
Security assessment for the ICAP OVA.

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-icap-ova-security#3]
Security assessment for the ICAP OVA.

**Comment by michaelhidalgo** [comment]
Hey @kumarsudhish , I will need instructions on how to access this ICAP OVA, so please be as detailed as possible so it is easier to get this started.

**Comment by michaelhidalgo** [comment]
I believe for this one the only pending task is to document the ports and the services listening on such ports that are strictly necessary.

As you can see, a brand new deployment of icap have below ports open. We need to document what is strictly needed:

![Screen Shot 2021-02-15 at 16 00 04](https://user-images.githubusercontent.com/1732035/108537632-769a6e00-72a3-11eb-93a4-5eea8a4dabb2.png)
.

![Screen Shot 2021-02-15 at 14 36 30](https://user-images.githubusercontent.com/1732035/108537603-6e423300-72a3-11eb-8ce3-1780d8b8ba29.png)

**Comment by gurunathg** [comment]
@michaelhidalgo I think there are more ports open but are blocked by Security group rules. There should opened ports at 80/443 for management UI. Can we modify SG to allow inbound connections to all ports and then perform nmap scan to see how many ports in instances are listening for connection?

**Comment by michaelhidalgo** [comment]
Yeah we could do that, but i believe from a documentation point of view, we should now what services are expected to listen for connections in order to ICAP to work. Think it like in terms of architecture and threat modeling point of view where from design we are identifying attack surface.

**Comment by gurunathg** [comment]
@michaelhidalgo Completely agree with you

**Comment by GINAGC** [comment]
Work completed
