### ISSUE TITLE
Test Scenario 1: To confirm that the ICAP server is able to work when ALL outbound traffic disabled (except the one initiated by inbound traffic to 443 and 1344)

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-icap-ova-security#4]
Test Scenario 1: To confirm that the ICAP server is able to work when ALL outbound traffic disabled (except the one initiated by inbound traffic to 443 and 1344)

**Comment by michaelhidalgo** [comment]
A document and video recording was created for this.  Over to you @kumarsudhish

**Comment by michaelhidalgo** [comment]
Hi @GINAGC can we close this one now?
