### ISSUE TITLE
Test Scenario  B : During and after server boot and under normal ICAP usage, traffic capture

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-icap-ova-security#5]
Test Scenario  B :  During and after server boot and under normal ICAP usage, the only traffic (inbound and outbound) that we see is the 443 and 1344 one (started from outbound, i.e. the server should NOT be doing any calls to any website)

**Comment by michaelhidalgo** [comment]
A video was created for this. The missing bits was to reboot the instance but overall video shows the idea. Over to you @kumarsudhish

**Comment by michaelhidalgo** [comment]
Hi @GINAGC can we close this one now?
