### ISSUE TITLE
Test Scenario  C : Generate some outbound traffic (ICMP, Http, random UDP and TCP ports) and show that ALL have been blocked

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-icap-ova-security#6]
Test Scenario  C :  We SSH into the box, and generate some outbound traffic (ICMP, Http, random UDP and TCP ports) and show that ALL have been blocked (i.e. marked as failed in the VPC Flow logs)

We SSH into the box, and generate some outbound traffic (ICMP, Http, random UDP and TCP ports) and show that ALL have been blocked (i.e. marked as failed in the VPC Flow logs)

**Comment by michaelhidalgo** [comment]
A video recording was created for this and an architecture doc was also released. over to you @kumarsudhish

**Comment by michaelhidalgo** [comment]
Hi @GINAGC can we close this one now?
